# Generated by Django 5.0.7 on 2025-09-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=255, unique=True)),
                ('anio', models.PositiveIntegerField(db_index=True)),
                ('genero', models.CharField(blank=True, max_length=255)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('actores', models.CharField(blank=True, max_length=512)),
                ('imdb_id', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('poster_url', models.URLField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
