# Generated by Django 5.0.7 on 2025-09-05 06:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviegame', '0002_alter_pelicula_options_intento_feedback_jugador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeliculaDelDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seleccionada_como_del_dia', to='moviegame.pelicula')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
